language: go

go:
  - tip

services:
  - postgresql: "9.4"

install:
  - make install

before_script:
  - psql -c "ALTER ROLE postgres WITH PASSWORD 'postgres';" -U postgres

script:
  - make test

notifications:
  email: false
  